name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'frontend-deployment'

env:
  VITE_BASE_URL: ${{vars.BASE_URL}}
  VITE_SUPABASE_KEY: ${{vars.SUPABASE_KEY}}
  VITE_SUPABASE_URL: ${{vars.SUPABASE_URL}}

permissions:
  contents: write

jobs:
  build-and-deploy:
    if: github.repository == 'SubxX/VoucherVault'
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: run build
        run: npx nx run dashboard:build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/apps/dashboard
